### ISSUE TITLE
Create test for algos

### ISSUE THREAD

**Issue by raphaelshirley** [LSSTDESC/rail_lephare#7]
We need a short unit test to test the informer and the estimator. Perhaps we can use the same example table as for rail_bpz.

**Comment by sschmidt23** [comment]
Just a note that the BPZ informer is doing something different than LePhare: the BPZ inform stage is actually training a Bayesian prior and outputting that parameterized model to be saved.  It is not loading any templates or anything like that, those bits are done in the estimate stage.  Just pointing out the difference, and that it might affect how you set things up.

**Comment by raphaelshirley** [comment]
Thanks that is an interesting difference. I actually saw that bpz was training a prior and thought that was an interesting idea for us to try as well. I will consider adding the template processing to the estimator stage. I had thought that the informer stage would do everything required for all objects and that estimate did all the per object processing but I will reconsider...

**Comment by sschmidt23** [comment]
I think it's just a design choice as to where to load things, I can see it making sense either way as to where to load and store the templates.  The main reason that I set things up the way I did was because the current version does not use the templates directly, and thus I can run the inform stage without loading the templates at all.  In the future I might modify things to add in a stage where I classify the spec-z galaxies based on the templates, at which point things might change to something more like what LePhare is doing.  But, for now, the way I have things implemented was way faster.
